# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }} && install dependencies
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }} && install dependencies
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

  # coverage:
  #   needs: [ build ]
  #   name: coverage
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@main
  #   - uses: actions/setup-node@main
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #   - run: sudo npm install -g yarn
  #   - run: sudo yarn install
  #   - run: sudo yarn add --dev jest         
  #   - uses: paambaati/codeclimate-action@v3.2.0
  #     env:
  #       CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
  #     with:
  #       coverageCommand: yarn test:coverage